version: '3.4'
services:

# ----------------------- SCRAPY AND RELATED SERVICES ----------------------- #

    scrapyd:
        image: vimagick/scrapyd:custom
        ports:
          - "6800:6800"
        volumes:
          - FIFA:/var/lib/scrapyd
          - source:/usr/local/lib/python3.7/dist-packages
        restart: always

    scrapy:
        image: vimagick/scrapyd:custom
        command: bash
        volumes:
          - code:/code
          - source:/usr/local/lib/python3.7/dist-packages
        working_dir: /code
        restart: always

    scrapyrt:
        image: vimagick/scrapyd:custom
        ports:
          - "9080:9080"
        volumes:
          - code:/code
          - source:/usr/local/lib/python3.7/dist-packages
        working_dir: /code
        command: scrapyrt -i 0.0.0.0 -p 9080
        #entrypoint: /code/entrypoint.sh
        restart: always

# -------------------------------- DATABASES -------------------------------- #

    redis:
        image: redis/rejson:5.0.3
        restart: always
        volumes:
          - /home/mohamed/.redis/data:/data
          - /home/mohamed/.redis/redis.conf:/usr/local/etc/redis/redis.conf
          - /var/log/redis/redis-server.log:/var/log/redis/redis-server.log
        ports:
          - "6379:6379"

    mongo_server:
        image: mongo:4.0.10
        restart: always
        volumes: 
          - /home/mohamed/.mongodb/data/db:/data/db
          - /home/mohamed/.mongodb/log/mongod.log:/data/configdb/mongod.log
          - /home/mohamed/.mongodb/mongod.conf:/data/configdb/mongod.conf
        command: >
          mongod 
          --config /data/configdb/mongod.conf 
          --dbpath /data/db 
          --logpath /data/configdb/mongod.log
          --logappend
        ports:
          - "27017:27017"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
        #     - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data/pgdata

# -------------------------------- WEBSERVERS-------------------------------- #

    webserver:
        image: puckel/docker-airflow:custom
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            - FIFA:/FIFA
            - ./requirements.txt:/requirements.txt
            - /home/mohamed/Project/FIFA/Docker/config/airflow.config:/usr/local/airflow/airflow.config
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:custom
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

# ------------------------- SCHEDULERS AND WORKSERS ------------------------- #

    scheduler:
        image: puckel/docker-airflow:custom
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - FIFA:/FIFA
            - ./requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: puckel/docker-airflow:custom
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - FIFA:/FIFA
            - ./requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker

# --------------------------------- VOLUMES --------------------------------- #

volumes:
  FIFA:
    name: FIFA
    driver_opts:
      type: none
      device: /home/mohamed/Projects/FIFA
      o: bind
  code:
    name: code
    driver_opts:
      type: none
      device: /home/mohamed/Projects/FIFA/fifa_data
      o: bind
  source:
    name: source
    driver_opts:
      type: none
      device: /home/mohamed/Projects/FIFA/source
      o: bind
