version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    # Custom mongo db
    mongo_server:
        image: mongo:3.6.3
        restart: always
        volumes: 
          - /data/db:/data/db
        ports:
          - "27017:27017"

    webserver:
        image: puckel/docker-airflow:1.10.1
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
            # Custom python package
            - ./requirements.txt:/requirements.txt
            # FIFA file path
            - ~/FIFA:/FIFA
            # Give access to docker.sock
            - /var/run/docker.sock:/var/run/docker.sock
        # Give privilege to run docker
        privileged: true
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
